### ISSUE TITLE
Double row

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-tabbed-sidebar#4]
I have installed the plug-in, but now have 2 rows:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/fe314b90-2c25-4563-8395-6f7be206c8e4)

I want to have only the tabbed row shown. I can do this:

```css
#right-sidebar .cp__right-sidebar-topbar {
  display: none;
}
```
which gives me this:

![image](https://github.com/sethyuan/logseq-plugin-tabbed-sidebar/assets/10794265/81e53c0b-530b-4b78-9b45-9df92e37f0f5)

It looks a bit funny. Is that the only/best way to do it?
